Orchestration monolith with 1 service and rest request v. 1.0
PJP24/PJP pull request #4
Opened 2024-12-09 09:08 UTC by romanvlad95

Created basic orchestrator monolith with only one service

2024-12-11 09:08 UTC, Slavkata requested changes

2024-12-11 09:08 UTC, Slavkata commented on api_services/user_service.py
> +                if response.user_id:
Use explicit if checks

2024-12-11 09:08 UTC, Slavkata commented on services/services.py
> +        if subscription_data:
Use explicit Ifs

2024-12-11 09:08 UTC, Slavkata commented on services/services.py
> +        if user_data:
Use explicit Ifs

2024-12-11 09:08 UTC, Slavkata commented on services/api.py
> +    if not user_id:
Use explicit Ifs

2024-12-11 13:14 UTC, romanvlad95 commented on services/api.py
> +    if not user_id:
Done, all inexplicit ifs are rewritten

2024-12-11 13:14 UTC, romanvlad95 commented on services/services.py
> +        if subscription_data:
Done, all inexplicit ifs are rewritten

2024-12-11 13:15 UTC, romanvlad95 commented on api_services/user_service.py
> +                if response.user_id:
Done, all inexplicit ifs are rewritten

2024-12-11 14:43 UTC, romanvlad95 commented
All messages are resolved

2024-12-12 14:51 UTC, Slavkata approved these changes

2024-12-13 14:46 UTC, Slavkata submitted a review, later dismissed

2024-12-13 15:43 UTC, Slavkata approved these changes

2024-12-13 15:45 UTC, merged